//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) {
        System.out.println("variable!");
        System.out.println("Задача 1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763729;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 2");
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 3");
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задача 5");
        var  frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("Задача 6");
        var boxer1Weight = 78.2;
        System.out.println(boxer1Weight);
        var boxer2Weight = 82.7;
        System.out.println(boxer2Weight);
        var totalWeight = boxer1Weight + boxer2Weight;
        System.out.println("Общая масса "+ totalWeight);
        var WeightDifference = boxer2Weight - boxer1Weight;
        System.out.println("Разница в массе "+ WeightDifference);
        System.out.println("Задача 7");
        var boxer1 = 78.2;
        System.out.println(boxer1);
        var boxer2 = 82.7;
        System.out.println(boxer2);
        var weightRemainder = boxer2 % boxer1;
        System.out.println("Остаток от деления между двумя вессами " + weightRemainder);
        System.out.println("Задача 8");
        var totalWorkTime = 640;
        System.out.println(totalWorkTime);
        var workTimeOnePeople = 8;
        System.out.println(workTimeOnePeople);
        var worker = totalWorkTime / workTimeOnePeople;
        System.out.println("Всего работников в компании " + worker + " человек");
        var workerCompany2 = worker + 94;
        System.out.println(workerCompany2);
        System.out.println("Если в компании работает " + workerCompany2 + " человека, то всего " + (workerCompany2 * 8) + " часов работы может быть поделено между сотрудниками");
    }
}